'use client';
import { useState } from 'react';
import { Activity, ArrowUpRight, Bell, Check, ChevronRight, CircleHelp, FileSearch, FolderOpen, LayoutDashboard, LockKeyhole, Menu, Radio, RotateCcw, Settings, Shield, ShieldCheck, Users, X } from 'lucide-react';
import { Provider, useTripwire } from './context';
import { Badge, Confirm, Countdown, Empty, money, PaymentStatus, RiskChart, RiskDial, SectionTitle, time, ViewLink } from './ui';
import { Protected } from './protected';
import { Inspector, Preferences, Relative } from './views';
import type { Payment } from '@/lib/types';

export type View = 'guardian' | 'protected' | 'relative' | 'inspector' | 'cases' | 'settings';
const names: Record<View, string> = { guardian: 'Command center', protected: 'Rosa’s shield', relative: 'Family callback', inspector: 'The Inspector', cases: 'Case files', settings: 'Family settings' };
export default function Tripwire({ view }: { view: View }) {
  const role = view === 'protected' || view === 'settings' ? 'protected' : view === 'relative' ? 'relative' : 'guardian';
  return <Provider role={role}><Shell view={view}/></Provider>;
}
function Shell({ view }: { view: View }) {
  const { state, error, setError, online } = useTripwire(); const [menu, setMenu] = useState(false);
  const urgent = state?.payments.filter(p => p.status === 'held').length || 0;
  const critical = state?.call.assessment.level === 'Critical' || urgent > 0;
  return <div className={`app-shell ${view === 'protected' || view === 'relative' ? 'simple-surface' : ''}`}>
    <a className="skip-link" href="#main">Skip to main content</a>
    {menu && <button className="sidebar-scrim" aria-label="Close navigation" onClick={() => setMenu(false)}/>}
    <aside className={'sidebar ' + (menu ? 'open' : '')}>
      <a className="brand" href="/"><div className="brand-mark">T<span/></div><span>tripwire<span className="brand-period">.</span><small>BEFORE THE MONEY MOVES</small></span></a>
      <div className="sidebar-family"><div className="avatar rosa">R</div><div><strong>The Garcia family</strong><small>3 people. One safety net.</small></div><ShieldCheck size={17}/></div>
      <div className="nav-label">OPERATIONS</div>
      <nav aria-label="Main navigation">
        {([{ id: 'guardian', label: 'Command center', icon: LayoutDashboard }, { id: 'protected', label: 'Rosa’s shield', icon: Shield }, { id: 'inspector', label: 'The Inspector', icon: FileSearch }, { id: 'cases', label: 'Case files', icon: FolderOpen }] as const).map(item => <a key={item.id} href={'/' + item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} aria-current={view === item.id ? 'page' : undefined}><item.icon size={19} strokeWidth={1.6}/>{item.label}{item.id === 'guardian' && urgent > 0 && <span className="nav-count">{urgent}</span>}</a>)}
      </nav>
      <div className="nav-label second">YOUR CREW</div><nav aria-label="Family navigation"><a href="/relative" className={'nav-item ' + (view === 'relative' ? 'active' : '')}><Users size={19}/>Family callback</a><a href="/settings" className={'nav-item ' + (view === 'settings' ? 'active' : '')}><Settings size={19}/>Family settings</a></nav>
      <div className="sidebar-bottom"><div className="crew-note"><span className="mini-cross">+</span><p>Every scam is a heist.<br/><strong>You have a crew.</strong></p></div><div className="sidebar-user"><div className="avatar elena">E</div><div><strong>{view === 'protected' || view === 'settings' ? 'Rosa Garcia' : view === 'relative' ? 'Alex Garcia' : 'Elena Garcia'}</strong><small>{view === 'protected' || view === 'settings' ? 'Protected family member' : view === 'relative' ? 'Trusted relative' : 'Family guardian'}</small></div></div></div>
    </aside>
    <div className="workspace">
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMenu(!menu)}><Menu size={22}/></button><span>GARCIA FAMILY</span><ChevronRight size={13}/><strong>{names[view]}</strong></div><div className="topbar-right"><span className={'connection ' + (online ? 'connected' : '')}><i/>{online ? 'Live connection' : 'Connecting…'}</span><Badge tone="outline">{state?.config.demo !== false ? 'DEMO MODE' : 'PAIRED MODE'}</Badge></div></header>
      {critical && <div className="laser-sweep" aria-hidden="true"/>}
      <main id="main" className="main-content">
        {error && <div role="alert" className="error-banner"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={() => setError('')}><X size={18}/></button></div>}
        {!state ? <div className="loading-state"><div className="brand-mark">T<span/></div><h1>Connecting your crew…</h1><p>Preparing the family shield.</p><button className="button secondary" onClick={() => window.location.reload()}>Retry connection</button></div> : <>
          {view === 'guardian' && <Dashboard/>}{view === 'protected' && <Protected/>}{view === 'relative' && <Relative/>}{view === 'inspector' && <Inspector/>}{view === 'cases' && <Cases/>}{view === 'settings' && <Preferences/>}
        </>}
      </main>
      <footer className="footer"><span><Shield size={13}/> BUILT FOR PEOPLE. BACKED BY THEIR PEOPLE.</span><span>ROWDYHACKS XII <i/> SAN ANTONIO, TX <i/> 2026</span></footer>
    </div>
  </div>;
}
function Dashboard() {
  const { state, request } = useTripwire(); const s = state!;
  const [reset, setReset] = useState(false);
  const held = s.payments.filter(p => p.status === 'held');
  const blocked = s.payments.filter(p => p.status === 'denied').reduce((sum, p) => sum + p.amount, 0);
  const protectedMoney = blocked + held.reduce((sum, p) => sum + p.amount, 0);
  const [tab, setTab] = useState<'signals' | 'transcript'>('signals');
  return <>
    <div className="page-heading"><div><p className="eyebrow"><span className="red-dash"/> THE COUNTER-HEIST CREW</p><h1>Every second counts<span>.</span></h1><p>Your family’s safety net, before the money moves.</p></div><a className="button primary" href="/protected"><Radio size={16}/>Open Rosa’s shield<ArrowUpRight size={16}/></a></div>
    <div className="overview-grid"><div className="stat-card"><div className="stat-top"><span>MONEY INTERRUPTED</span><ShieldCheck size={18}/></div><strong>{money(protectedMoney)}<span className="stat-unit">USD</span></strong><p><span className="green-dot"/>{money(blocked)} blocked · {money(protectedMoney - blocked)} on hold</p></div><div className="stat-card"><div className="stat-top"><span>NEEDS YOUR ATTENTION</span><Bell size={18}/></div><strong>{String(held.length).padStart(2, '0')}<span className="stat-note">{held.length ? 'Your second key is needed' : 'You’re all caught up'}</span></strong><p>{held.length ? 'Review the payment queue below' : 'We’ll flag requests that need a closer look'}</p></div><div className="stat-card family-stat"><div className="stat-top"><span>YOUR INNER CIRCLE</span><Users size={18}/></div><div className="family-avatars"><div className="avatar rosa">R</div><div className="avatar elena">E</div><div className="avatar alex">A</div><div><strong>3 family members</strong><small>Rosa, Elena & Alex</small></div></div><p>Different roles. The same side.</p></div></div>
    <div className="dashboard-columns"><div className="left-column">
      <section className="panel lookout-panel"><SectionTitle index="01" title="The Lookout" right={<Badge tone={s.call.active ? 'green' : 'neutral'}><span className={s.call.active ? 'live-dot' : ''}/>{s.call.active ? 'CALL GUARD ACTIVE' : 'STANDING BY'}</Badge>}/><div className="lookout-body"><div className="risk-summary"><RiskDial score={s.call.assessment.score} level={s.call.assessment.level}/><div className="risk-copy"><p className="eyebrow">ROSA’S CALL GUARD</p><h3>{s.call.assessment.score >= 85 ? 'Something isn’t adding up.' : s.call.active ? 'Listening for the tells.' : 'A little backup. A lot of peace of mind.'}</h3><p>{s.call.active || s.call.assessment.score ? s.call.assessment.advice : 'When Rosa starts the call guard, you’ll see warning signs here as they happen.'}</p><div className="source-label"><Activity size={13}/>{s.call.assessment.source === 'gemini' ? 'Gemini + deterministic rules' : 'Deterministic risk engine'}<span>•</span>{s.call.active ? 'Live session' : 'No active call'}</div></div></div><div className="chart-heading"><span>RISK OVER TIME</span><span className="critical-key">— CRITICAL AT 85</span></div><RiskChart events={s.events}/></div><div className="lookout-tabs"><button className={tab === 'signals' ? 'selected' : ''} onClick={() => setTab('signals')}>Detected signals <span>{s.call.assessment.tells.length}</span></button><button className={tab === 'transcript' ? 'selected' : ''} onClick={() => setTab('transcript')}>Live transcript</button></div><div className="signal-area">{tab === 'signals' ? s.call.assessment.tells.length ? <div className="tell-chips">{s.call.assessment.tells.map(t => <span key={t.id}><span className="signal-dot"/>{t.label}</span>)}</div> : <p className="quiet-text">No signals yet. Start a demo call in Rosa’s shield to see the Lookout in action.</p> : <div className="transcript-mini">{s.call.transcript.length ? s.call.transcript.map(l => <p key={l.id}><time>{time(l.at)}</time>{l.text}</p>) : <p className="quiet-text">Live text appears here with the protected user’s consent. It is not saved by default.</p>}</div>}</div></section>
      <section className="panel"><SectionTitle index="02" title="The Two-Key Rule" right={<Badge tone="outline">PAYMENT QUEUE</Badge>}/><div className="queue-description"><LockKeyhole size={15}/><span>A moment to pause. A person to check with.</span></div><PaymentQueue/></section>
    </div><div className="right-column">
      <section className="demo-card"><div className="demo-card-top"><span className="eyebrow">FIELD EXERCISE / 001</span><span className="target-symbol">⊕</span></div><h2>Meet the con.<br/>Trip the alarm.</h2><p>One worried grandma. One fake emergency. One crew that catches it in time.</p><a href="/protected" className="button paper">Run the grandson demo<ArrowUpRight size={17}/></a><div className="demo-fine"><span/>SCRIPTED SCENARIO · NO REAL MONEY</div></section>
      <section className="panel activity-panel"><SectionTitle index="03" title="The wire" right={<span className="mono-small">LIVE LOG</span>}/><div className="activity-list">{s.events.length ? s.events.slice(-6).reverse().map((event, i) => <div className="activity-event" key={event.id}><div className={'event-node ' + (i === 0 ? 'latest' : '')}>{event.kind === 'payment' ? <LockKeyhole size={13}/> : event.kind === 'verification' ? <Check size={13}/> : <Radio size={13}/>}</div><div><p>{event.label}</p><time>{time(event.at)} <span>·</span> {event.kind.toUpperCase()}</time></div></div>) : <div className="activity-waiting"><Radio size={23}/><p>The wire is quiet.</p><span>Calls, checks, and payment decisions will appear here.</span></div>}</div></section>
      <div className="empathy-note"><CircleHelp size={19}/><p>“You did nothing wrong.<br/>These callers are professionals.”<span>EMPATHY IS THE STRATEGY.</span></p></div>
    </div></div>
    <section className="family-strip"><div><div className="avatar rosa">R</div><span><strong>Rosa Garcia</strong><small>Protected member</small></span><Badge tone="neutral">{s.call.active ? 'CALL GUARD ON' : 'READY WHEN NEEDED'}</Badge></div><div><Users size={20}/><p>The best alarm is a familiar voice.</p></div><ViewLink href="/relative">Open Alex’s callback view</ViewLink></section>
    <div className="demo-bottom"><p className="demo-disclosure">Demo household · Mock payments · Local SQLite holds · No funds move. {s.config.gemini ? 'Gemini configured.' : 'Rules fallback active.'} {s.config.elevenlabs ? 'ElevenLabs configured.' : 'Browser voice available.'}</p>{s.config.demo && <button className="text-link" onClick={() => setReset(true)}><RotateCcw size={12}/>Reset demo</button>}</div>
    <Confirm open={reset} title="Start with a clean caseboard?" label="Reset demo" onClose={() => setReset(false)} action={async () => { await request('/demo/reset'); }}><p>This clears demo calls, payments, and case files. Your family safe word stays configured. No real money is involved.</p></Confirm>
  </>;
}
export function PaymentQueue() {
  const { state, request } = useTripwire(); const [decision, setDecision] = useState<{ payment: Payment; action: 'approve' | 'deny' } | null>(null);
  const payments = state!.payments.slice(0, 6);
  return <><div className="payment-queue">{payments.length ? payments.map(p => <article className={'payment-item ' + p.status} key={p.id}><div className="payment-item-top"><div className="payment-symbol"><LockKeyhole size={21}/></div><div className="payment-who"><h3>{p.payee}</h3><p>{p.rail.replace('-', ' ')} <span>·</span> {time(p.createdAt)}</p></div><strong>{money(p.amount)}</strong></div><div className="payment-meta"><PaymentStatus payment={p}/>{p.status === 'held' && p.releaseAt && <span>Cooling off <Countdown until={p.releaseAt}/></span>}</div><p className="payment-summary">{p.summary}</p>{(p.status === 'held' || p.status === 'review') && <div className="button-row"><button className="button primary" onClick={() => setDecision({ payment: p, action: 'deny' })}><ShieldCheck size={15}/>Deny payment</button><button className="button secondary" onClick={() => setDecision({ payment: p, action: 'approve' })}>Approve after verifying</button></div>}</article>) : <Empty title="No payments need a second key.">Risky requests will wait here for your decision. Routine payments can carry on.</Empty>}</div><Confirm open={!!decision} title={decision?.action === 'deny' ? 'Stop this payment?' : 'Have you verified this request?'} label={decision?.action === 'deny' ? 'Deny payment' : 'Approve payment'} onClose={() => setDecision(null)} action={async () => { if (decision) await request('/payments/decide', { id: decision.payment.id, decision: decision.action }); }}><p>{decision?.action === 'deny' ? `This cancels the ${money(decision.payment.amount)} demo payment to ${decision.payment.payee}. Rosa will see your decision immediately.` : 'Call Rosa on a number you trust first. Approval releases this mock payment immediately and cannot be undone in the demo.'}</p></Confirm></>;
}
function Cases() {
  const { state } = useTripwire(); const s = state!; const [filter, setFilter] = useState('all');
  const cases = s.cases.filter(c => filter === 'all' || c.outcome === filter);
  return <><div className="page-heading"><div><p className="eyebrow">EVIDENCE / EDUCATION / A LITTLE CLOSURE</p><h1>The case files<span>.</span></h1><p>Know the playbook. Recognize the next attempt.</p></div><Badge tone="outline">{s.cases.length} FILES ON RECORD</Badge></div><div className="filter-tabs">{['all', 'open', 'foiled', 'reviewed'].map(f => <button className={filter === f ? 'selected' : ''} key={f} onClick={() => setFilter(f)}>{f === 'all' ? 'All files' : f === 'foiled' ? 'Heists foiled' : f}</button>)}</div><div className="case-grid">{cases.map((c, i) => <article className="case-card" key={c.id}><div className="case-tab">CONFIDENTIAL · FAMILY COPY</div><div className="case-card-top"><span className="eyebrow">FILE {String(s.cases.length - s.cases.indexOf(c)).padStart(3, '0')}</span><Badge tone={c.outcome === 'foiled' ? 'green' : 'neutral'}>{c.outcome}</Badge></div><h2>{c.title}</h2><p className="case-date">{new Date(c.openedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} / {time(c.openedAt)}</p><div className="case-divider"/><p className="eyebrow">THE TELLS</p><ul>{c.tells.map(t => <li key={t}>{t}</li>)}</ul><div className="case-lesson"><Shield size={18}/><p>Next time: pause, check with someone you trust, and call back using a saved number.</p></div>{c.outcome === 'foiled' && <div className="foiled-stamp">HEIST FOILED</div>}<span className="case-number" aria-hidden="true">{String(i + 1).padStart(2, '0')}</span></article>)}</div>{!cases.length && <section className="panel"><Empty title="A clean slate.">Run a demo in Rosa’s shield. A flagged payment creates a case file with the patterns to recognize next time.</Empty></section>}</>;
}
