import { mkdirSync, existsSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { Keypair } from '@solana/web3.js';
const directory = '.solana-private';
mkdirSync(directory, { recursive: true, mode: 0o700 }); chmodSync(directory, 0o700);
const path = directory + '/deployer.json';
if (!existsSync(path)) writeFileSync(path, JSON.stringify([...Keypair.generate().secretKey]), { mode: 0o600, flag: 'wx' });
chmodSync(path, 0o600);
const wallet = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(path, 'utf8'))));
console.log(JSON.stringify({ cluster: 'devnet', deployer: wallet.publicKey.toBase58(), keypairPath: path }));
console.log('Keep this deployment/upgrade key private and off Vultr. Only public addresses belong in repository variables.');
